In [6]:
using CSV
using DataFrames
using Dates
using LinearAlgebra
using Plots
using Statistics

In [7]:
df_path= joinpath("current.csv")
df = CSV.read(df_path, DataFrame)

785×127 DataFrame
 Row │ sasdate     RPI       W875RX1  DPCERA3M086SBEA  CMRMTSPLx        RETAIL ⋯
     │ String15    Float64   Float64  Float64          Float64?         Float6 ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ Transform:      5.0       5.0            5.0          5.0             5 ⋯
   2 │ 1/1/1959     2583.56   2426.0           15.188        2.76677e5   18235
   3 │ 2/1/1959     2593.6    2434.8           15.346   278714.0         18369
   4 │ 3/1/1959     2610.4    2452.7           15.491        2.77775e5   18523
   5 │ 4/1/1959     2627.45   2470.0           15.435        2.83363e5   18534 ⋯
   6 │ 5/1/1959     2642.72   2486.4           15.622        2.85307e5   18679
   7 │ 6/1/1959     2650.84   2493.9           15.679        2.8528e5    18849
   8 │ 7/1/1959     2649.3    2492.0           15.626        2.88768e5   18843
   9 │ 8/1/1959     2634.37   2477.7           15.72         2.73993e5   18963 ⋯
  10 │ 9/1/1959     2636.38   2477.7           15.878        2.78039e5   18716
  11 │ 10/1/1959    2639.74   2480.6           15.77         2.7849e5    18852
  ⋮  │     ⋮          ⋮         ⋮            ⋮                ⋮            ⋮   ⋱
 776 │ 7/1/2023    19095.9   15691.7          116.235        1.50022e6  690408
 777 │ 8/1/2023    19117.5   15726.6          116.171        1.49772e6  695476 ⋯
 778 │ 9/1/2023    19111.7   15741.9          116.594        1.50753e6  701286
 779 │ 10/1/2023   19116.0   15749.7          116.773        1.50479e6  699977
 780 │ 11/1/2023   19161.0   15795.9          117.258        1.51412e6  700707
 781 │ 12/1/2023   19194.7   15823.3          117.796        1.52399e6  703256 ⋯
 782 │ 1/1/2024    19326.1   15868.0          117.445        1.50453e6  695631
 783 │ 2/1/2024    19315.8   15835.4          117.822        1.50902e6  700519
 784 │ 3/1/2024    19353.4   15858.4          118.302        1.50775e6  705057
 785 │ 4/1/2024    19356.9   15858.9          118.238  missing          705180 ⋯
                                                122 columns and 764 rows omitted

In [8]:
### Clean the DataFrame by removing the row with transformation codes
df_cleaned = df[2:end, :]
date_format = "mm/dd/yyyy"
df_cleaned[!, :sasdate] = Dates.Date.(df_cleaned[!, :sasdate], date_format)

df_original = copy(df_cleaned)
df_cleaned = coalesce.(df_cleaned, NaN)
df_original = coalesce.(df_original, NaN)
### Create a DataFrame with the transformation codes
transformation_codes = DataFrame(Series = names(df)[2:end],  Transformation_Code = collect(df[1, 2:end]))

126×2 DataFrame
 Row │ Series           Transformation_Code 
     │ String           Real                
─────┼──────────────────────────────────────
   1 │ RPI                              5.0
   2 │ W875RX1                          5.0
   3 │ DPCERA3M086SBEA                  5.0
   4 │ CMRMTSPLx                        5.0
   5 │ RETAILx                          5.0
   6 │ INDPRO                           5.0
   7 │ IPFPNSS                          5.0
   8 │ IPFINAL                          5.0
   9 │ IPCONGD                          5.0
  10 │ IPDCONGD                         5.0
  11 │ IPNCONGD                         5.0
  ⋮  │        ⋮                  ⋮
 117 │ DNDGRG3M086SBEA                  6.0
 118 │ DSERRG3M086SBEA                  6.0
 119 │ CES0600000008                    6.0
 120 │ CES2000000008                    6.0
 121 │ CES3000000008                    6.0
 122 │ UMCSENTx                         2.0
 123 │ DTCOLNVHFNM                      6.0
 124 │ DTCTHFNM                         6.0
 125 │ INVEST                           6.0
 126 │ VIXCLSx                          1.0
                            105 rows omitted

In [9]:
### Function to apply transformations based on the transformation code
function apply_transformation(series, code)
    if code == 1
        # No transformation
        return series
    elseif code == 2
        # First difference
        return mdiff(series)
    elseif code == 3
        # Second difference
        return mdiff(mdiff(series))
    elseif code == 4
        # Log
        return log.(series)
    elseif code == 5
        # First difference of log
        return mdiff(log.(series))
    elseif code == 6
        # Second difference of log
        return mdiff(mdiff(log.(series)))
    elseif code == 7
        # Delta (x_t/x_{t-1} - 1)
        return series ./ lag(series, 1) .- 1
    else
        throw(ArgumentError("Invalid transformation code"))
    end
end

apply_transformation (generic function with 1 method)

In [10]:
### Helper function to lag a series (since Julia doesn't have a built-in function to lag)
function lag(v::Vector, l::Integer)
    nan = [NaN for _ in 1:l]
    return [nan; v[1:(end-l)]]
end

function lead(v::Vector, l::Integer)
    nan = [NaN for _ in 1:l]
    return [v[(l+1):end]; nan]
end

### mdiff function to calculate the first difference of a series
function mdiff(v::Vector)
    return v .- lag(v, 1)
end

### Applying the transformations to each column in df_cleaned based on transformation_codes
for row in eachrow(transformation_codes)
    series_name = Symbol(row[:Series])
    code = row[:Transformation_Code]
    @show series_name, code
    df_cleaned[!, series_name] = apply_transformation(df_cleaned[!, series_name], code)
end

(series_name, code) = (:RPI, 5.0)
(series_name, code) = (:W875RX1, 5.0)
(series_name, code) = (:DPCERA3M086SBEA, 5.0)
(series_name, code) = (:CMRMTSPLx, 5.0)
(series_name, code) = (:RETAILx, 5.0)
(series_name, code) = (:INDPRO, 5.0)
(series_name, code) = (:IPFPNSS, 5.0)
(series_name, code) = (:IPFINAL, 5.0)
(series_name, code) = (:IPCONGD, 5.0)
(series_name, code) = (:IPDCONGD, 5.0)
(series_name, code) = (:IPNCONGD, 5.0)
(series_name, code) = (:IPBUSEQ, 5.0)
(series_name, code) = (:IPMAT, 5.0)
(series_name, code) = (:IPDMAT, 5.0)
(series_name, code) = (:IPNMAT, 5.0)
(series_name, code) = (:IPMANSICS, 5.0)
(series_name, code) = (:IPB51222S, 5.0)
(series_name, code) = (:IPFUELS, 5.0)
(series_name, code) = (:CUMFNS, 2.0)
(series_name, code) = (:HWI, 2)
(series_name, code) = (:HWIURATIO, 2.0)
(series_name, code) = (:CLF16OV, 5)
(series_name, code) = (:CE16OV, 5)
(series_name, code) = (:UNRATE, 2.0)
(series_name, code) = (:UEMPMEAN, 2.0)
(series_name, code) = (:UEMPLT5, 5)
(series_name, cod

In [11]:
### The transformation create missing values at the top, so let's remove them
df_cleaned = df_cleaned[3:end, :]

function compute_forecast(target = :INDPRO, x_var = [:CPIAUCSL, :FEDFUNDS],H = [1 4 8],p = 4)
    y_hat=[]

    y_raw = df_cleaned[!, target]
    x_raw = select(df_cleaned, x_var)    

    Y_lagged = hcat([lag(y_raw, p) for i in 1:p]...)
    X_lagged = hcat([lag(x_raw[:, j], i) for j in 1:size(x_raw, 2) for i in 1:p]...)
    
    X = hcat(ones(size(Y_lagged, 1)), Y_lagged, X_lagged)
  
    X_T = X[end, :]
    
    for h in H
        y_h = lead(y_raw, h)
        y  = y_h[p+1:(end-h)]
        X_ = X[p+1:(end-h), :]
        beta_ols = X_ \ y
        forecast = (X_T' * beta_ols) * 100
        push!(y_hat,forecast)  
    end
    return y_hat
end

compute_forecast (generic function with 5 methods)

In [12]:
# CREATE THE FORECASTING FUNCTION
function compute_error(target = :INDPRO, x_var = [:CPIAUCSL, :FEDFUNDS],H = [1 4 8],p = 4, end_date = Dates.Date("12/01/1999", date_format))
    y_hat = []
    y_actual = []
    rt_df = filter(row -> row[:sasdate] <= end_date, df_cleaned)
    

    for h in H
        os = end_date + Dates.Month(h)
        push!(y_actual, (filter(row -> row[:sasdate] == os, df_cleaned)))
    end

    y_raw = rt_df[!, target]
    x_raw = select(rt_df, x_var)    

    Y_lagged = hcat([lag(y_raw, p) for i in 1:p]...)
    X_lagged = hcat([lag(x_raw[:, j], i) for j in 1:size(x_raw, 2) for i in 1:p]...)
    
    X = hcat(ones(size(Y_lagged, 1)), Y_lagged, X_lagged)
  
    X_T = X[end, :]
    
    for h in H
        y_h = lead(y_raw, h)
        y  = y_h[p+1:(end-h)]
        X_ = X[p+1:(end-h), :]
        beta_ols = X_ \ y
        forecast = (X_T' * beta_ols) * 100
        push!(y_hat,forecast)  
    end
    
    y_actual_matrix = vcat(y_actual[1],y_actual[2],y_actual[3])
    error_value = y_hat - y_actual_matrix[!,target] 
    error_value = hcat(error_value)
    
    return error_value
    

end

compute_error (generic function with 6 methods)

In [13]:
# CREATE THE ERROR-COMPUTING FUNCTION
function evaluate_model(target = :INDPRO, x_var = [:CPIAUCSL, :FEDFUNDS],H = [1 4 8],p = 4, t0 = "12/01/1999")

    t0 = Dates.Date(t0,date_format)
    e = []
    T = []
   

    for j in 1:10
        t0 = t0 + Dates.Month(1)
        ehat = compute_error(target,x_var,H,p, t0)
        ehat = ehat'
        push!(e,ehat)
        push!(T,t0)
    end
    a = vcat(e...)
    sqrd_a = a .^ 2
    mean_sqrd_a = (mean(sqrd_a, dims=1)) .^(0.5)
    return  mean_sqrd_a

end


evaluate_model (generic function with 6 methods)

In [14]:

# COMPUTING THE 3 DIFFERENT REGRESSIONS
forecast_INDPRO = compute_forecast(:INDPRO, [:CPIAUCSL, :TB3MS, :AWHMAN])
println(forecast_INDPRO)
forecast_CPI= compute_forecast(:CPIAUCSL, [:M1SL, :UNRATE, :FEDFUNDS, :OILPRICEx])
println(forecast_CPI)
forecast_FF = compute_forecast(:FEDFUNDS, [:CPIAUCSL, :UNRATE, :INDPRO, :TB3MS, :INVEST, :DTCTHFNM, :NONREVSL, :PCEPI])
println(forecast_FF)

regressione1 = evaluate_model(:INDPRO, [:CPIAUCSL, :TB3MS, :AWHMAN])
println(regressione1)
regressione2 = evaluate_model(:CPIAUCSL, [:M1SL, :UNRATE, :FEDFUNDS, :OILPRICEx])
println(regressione2)
regressione3 = evaluate_model(:FEDFUNDS, [:CPIAUCSL, :UNRATE, :INDPRO, :TB3MS, :INVEST, :DTCTHFNM, :NONREVSL, :PCEPI])
println(regressione3)

Any[0.2425919059177481, 0.2912798088947899, 0.3252145273681714]
Any[-0.05643642398835013, 0.016930926642984335, 0.024599526152021916]
Any[8.225458821562086, -9.061173052372075, 26.14034411702213]
[0.3756036287054008 0.2931728496467193 0.25259659198416234]
[0.054932098090677735 0.07494818306843783 0.042703124051111194]
[6.588976477676038 6.399557205697552 10.29328847434379]
